In [1]:
import pandas as pd

In [2]:
OLD_STOCK_DIR = '../data/stock_daily.parquet'
NEW_STOCK_DIR = '../data/vn_stock_price_daily_yahoo.parquet'

In [3]:
df_old = pd.read_parquet(OLD_STOCK_DIR)
df_new = pd.read_parquet(NEW_STOCK_DIR)

In [4]:
df_old.head()

        time  close  volume stock_code     EMA20     EMA50    EMA200
0 2016-08-12    0.0  521300        GEX  7.669225  8.244786  8.201011
1 2009-09-16    0.0       0        MAS  8.531905  9.060196  9.336169
2 2010-05-18    0.0       0        MAS  5.687326  6.739344  8.621333
3 2010-04-14    0.0       0        MAS  6.162990  7.925441  9.250020
4 2010-06-16    0.0     277        MAS  5.346192  6.158499  8.164310

In [12]:
df_old[(df_old['stock_code'] == 'VIC') & (df_old['time'] > '2016-01-01')].sort_values('time').head()

             time  close   volume stock_code      EMA20      EMA50     EMA200
380497 2016-01-04  12.83  4809120        VIC  11.753026  11.646042  11.284299
380496 2016-01-05  12.83  2480100        VIC  11.855595  11.692472  11.299679
380498 2016-01-06  12.83  1976280        VIC  11.948395  11.737081  11.314907
383101 2016-01-07  12.97  2852010        VIC  12.045691  11.785430  11.331375
383104 2016-01-08  12.97  1641950        VIC  12.133720  11.831884  11.347680

In [10]:
df_new[df_new['stock_code'] == 'VIC'].head()

,time,close,volume,stock_code,yahoo_symbol,EMA20,EMA50,EMA200
336204,2016-01-04,12831.181641,17802974,VIC,VIC.VN,12831.181641,12831.181641,12831.181641
336205,2016-01-05,12831.181641,9181130,VIC,VIC.VN,12831.181641,12831.181641,12831.181641
336206,2016-01-06,12831.181641,7316029,VIC,VIC.VN,12831.181641,12831.181641,12831.181641
336207,2016-01-07,12966.247070,10557911,VIC,VIC.VN,12844.045015,12836.478324,12832.525575
336208,2016-01-08,12966.247070,6078366,VIC,VIC.VN,12855.683306,12841.567295,12833.856137

In [13]:
df_new['close'] = df_new['close'] / 1000
df_new['EMA20'] = df_new['EMA20'] / 1000
df_new['EMA50'] = df_new['EMA50'] / 1000
df_new['EMA200'] = df_new['EMA200'] / 1000

In [17]:
df_old_stock_code = set(df_old['stock_code'].unique())
df_new_stock_code = set(df_new['stock_code'].unique())

In [15]:
df_old_stock_code

{'AAA',
 'AAM',
 'ABB',
 'ABT',
 'ACB',
 'ACL',
 'ACV',
 'AGG',
 'AGR',
 'ANV',
 'APG',
 'ASM',
 'BAF',
 'BCM',
 'BID',
 'BMP',
 'BSR',
 'BVB',
 'BWE',
 'CAP',
 'CEO',
 'CII',
 'CLL',
 'CMG',
 'CMX',
 'CNG',
 'CRE',
 'CSV',
 'CTD',
 'CTG',
 'CTI',
 'CTR',
 'CTS',
 'D2D',
 'DBC',
 'DCM',
 'DGC',
 'DGW',
 'DHT',
 'DIG',
 'DPG',
 'DPM',
 'DRI',
 'DSE',
 'DTD',
 'DVM',
 'DXG',
 'EIB',
 'ELC',
 'EVF',
 'FIT',
 'FMC',
 'FOX',
 'FPT',
 'FRT',
 'GAS',
 'GEE',
 'GEX',
 'GMD',
 'GVR',
 'HAG',
 'HAH',
 'HBC',
 'HCM',
 'HDB',
 'HDC',
 'HDG',
 'HLD',
 'HPG',
 'HPX',
 'HSG',
 'HT1',
 'HTN',
 'HUT',
 'IDI',
 'IJC',
 'ILB',
 'IMP',
 'ITC',
 'ITD',
 'KBC',
 'KDC',
 'KDH',
 'KLB',
 'KOS',
 'L14',
 'L18',
 'LAS',
 'LBM',
 'LCG',
 'LDG',
 'LHC',
 'LPB',
 'MAS',
 'MBB',
 'MBS',
 'MSB',
 'MSH',
 'MSN',
 'MWG',
 'NAB',
 'NHA',
 'NKG',
 'NLG',
 'NRC',
 'NT2',
 'NTP',
 'NVB',
 'NVL',
 'OCB',
 'ORS',
 'PAN',
 'PC1',
 'PDR',
 'PET',
 'PGB',
 'PHR',
 'PLC',
 'PLX',
 'PNJ',
 'POW',
 'PPC',
 'PSD',
 'PSH',
 'PTB',
 'PVC',
 'PVD',
 'PVG',
 'PVP',
 'PVS',
 'PVT',
 'RAL',
 'REE',
 'SAB',
 'SAF',
 'SAM',
 'SBT',
 'SCR',
 'SGB',
 'SGP',
 'SGT',
 'SHB',
 'SHS',
 'SIP',
 'SJS',
 'SLS',
 'SSI',
 'STB',
 'STK',
 'SZC',
 'TCB',
 'TCH',
 'TCM',
 'TDG',
 'TIG',
 'TIS',
 'TLH',
 'TMB',
 'TMS',
 'TNG',
 'TPB',
 'TTF',
 'TTN',
 'TVD',
 'TVN',
 'TVS',
 'UIC',
 'VAB',
 'VC3',
 'VCB',
 'VCG',
 'VCI',
 'VCS',
 'VDS',
 'VGC',
 'VGI',
 'VGS',
 'VHC',
 'VHM',
 'VIB',
 'VIC',
 'VIP',
 'VIX',
 'VJC',
 'VLC',
 'VND',
 'VNM',
 'VOS',
 'VPB',
 'VPI',
 'VRE',
 'VSC',
 'VTE',
 'VTO',
 'VTP',
 'YEG'}

In [16]:
len(df_old_stock_code)

196

In [18]:
diff_stock_code = df_new_stock_code - df_old_stock_code
diff_stock_code

{'ACC',
 'ACG',
 'ADP',
 'ADS',
 'AFX',
 'AST',
 'C32',
 'CCL',
 'CHP',
 'CIG',
 'CKG',
 'CVT',
 'DAH',
 'DBD',
 'DC4',
 'DHA',
 'DHC',
 'DHG',
 'DMC',
 'DQC',
 'DRC',
 'DRL',
 'DSN',
 'EVE',
 'FCN',
 'GIL',
 'GSP',
 'HAP',
 'HAX',
 'HHP',
 'HHV',
 'HQC',
 'HTG',
 'JVC',
 'LGL',
 'LHG',
 'LSS',
 'NAF',
 'NCT',
 'NHH',
 'NTC',
 'PDN',
 'PGD',
 'PHC',
 'PJT',
 'PTC',
 'PTL',
 'QCG',
 'SAV',
 'SBG',
 'SCS',
 'SMC',
 'SRF',
 'SSB',
 'SVC',
 'TAL',
 'TCI',
 'TCL',
 'TCR',
 'TCT',
 'TCX',
 'TDM',
 'TDP',
 'THG',
 'TIP',
 'TMT',
 'TNI',
 'TRA',
 'TRC',
 'TVB',
 'TYA',
 'VPD',
 'VPH'}

In [19]:
df_new_new = df_new[df_new['stock_code'].isin(diff_stock_code)]
df_new_new.head()

,time,close,volume,stock_code,yahoo_symbol,EMA20,EMA50,EMA200
5154,2016-01-04,7.435430,1979,ACC,ACC.VN,7.435430,7.435430,7.435430
5155,2016-01-05,7.338446,247,ACC,ACC.VN,7.426193,7.431626,7.434465
5156,2016-01-06,7.209134,23385,ACC,ACC.VN,7.405521,7.422901,7.432223
5157,2016-01-07,7.176806,1608,ACC,ACC.VN,7.383738,7.413250,7.429681
5158,2016-01-08,7.176806,247,ACC,ACC.VN,7.364031,7.403978,7.427165

In [20]:
df_new_new.drop(columns=['yahoo_symbol'], inplace=True)

/var/folders/y0/d5yxmby14p1b51jsfj3ml2vr0000gn/T/ipykernel_67588/2445971409.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_new.drop(columns=['yahoo_symbol'], inplace=True)

In [21]:
df_new_new.to_parquet('../data/stock_price_daily_yahoo.parquet', index=False)

In [37]:
DF_INFO_OLD = "/Users/quanghung20gg/code/finance-agent/data_collection/financial_statement/transform/metadata/df_company_info.csv"
DF_INFO_NEW = "/Users/quanghung20gg/code/finance-agent/data_collection/financial_statement/transform/metadata/missing_yahoo_company_names_vn.csv"

df_info_old = pd.read_csv(DF_INFO_OLD)
df_info_new = pd.read_csv(DF_INFO_NEW)

In [38]:
df_info_old.head()

,stock_code,company_name,short_name,en_company_name,en_short_name,combine_profile,industry,exchange,foreign_percent,issue_share,no_shareholders,stock_rating,website,stock_indices,is_bank,is_securities
0,BID,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,BIDV,Joint Stock Commercial Bank for Investment and...,BIDV,company_name: Ngân hàng Thương mại Cổ phần Đầu...,Banking,HOSE,0.168,6.897500e+09,27603.0,3.0,https://www.bidv.com.vn,VN30,True,False
1,EIB,Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Vi...,Eximbank,Vietnam Export Import Commercial Joint Stock Bank,Eximbank,company_name: Ngân hàng Thương mại Cổ phần Xuấ...,Banking,HOSE,0.026,1.868800e+09,25371.0,3.1,https://eximbank.com.vn,OTHER,True,False
2,OCB,Ngân hàng Thương mại Cổ phần Phương Đông,Ngân hàng Phương Đông,Orient Commercial Joint Stock Bank,OCB Bank,company_name: Ngân hàng Thương mại Cổ phần Phư...,Banking,HOSE,0.200,2.465800e+09,20103.0,2.6,https://www.ocb.com.vn,OTHER,True,False
3,CTG,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,VietinBank,Vietnam Joint Stock Commercial Bank For Indust...,VietinBank,company_name: Ngân hàng Thương mại Cổ phần Côn...,Banking,HOSE,0.268,5.370000e+09,53928.0,3.5,http://www.vietinbank.vn,VN30,True,False
4,VCB,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,Vietcombank,Joint Stock Commercial Bank For Foreign Trade ...,Vietcombank,company_name: Ngân hàng Thương mại Cổ phần Ngo...,Banking,HOSE,0.228,5.589100e+09,25183.0,2.7,https://vietcombank.com.vn,VN30,True,False

In [39]:
df_info_old['industry'].unique()

array(['Banking', 'Basic Resources', 'Information Technology',
       'Industrial Goods and Services',
       'Utilities (Electricity, Water & Gas)', 'Real Estate', 'Chemicals',
       'Food and Beverages', 'Oil and Gas', 'Telecommunications',
       'Construction and Materials', 'Retail',
       'Personal and Household Goods', 'Media', 'Travel and Leisure',
       'Healthcare', 'Automobiles and Parts', 'Financial Services', nan],
      dtype=object)

In [40]:
df_info_new.head()

,symbol,full_name_vi,short_name_vi,english_name,is_bank,is_securities,exchange,stock_indices,industry
0,ABC,Công ty Cổ phần Truyền thông VMG,VMG Media,VMG Media Joint Stock Company,False,False,UPCOM,OTHER,Media
1,ACV,Tổng công ty Cảng hàng không Việt Nam - CTCP,ACV,Airports Corporation of Vietnam,False,False,UPCOM,OTHER,Travel and Leisure
2,AMS,Công ty Cổ phần Cơ khí Xây dựng AMECC,AMECC JSC,AMECC Mechanical Construction Joint Stock Company,False,False,UPCOM,OTHER,Industrial Goods and Services
3,APF,Công ty Cổ phần Nông sản Thực phẩm Quảng Ngãi,APFCO,Quang Ngai Agricultural Products and Foodstuff...,False,False,UPCOM,OTHER,Food and Beverages
4,AVC,Công ty Cổ phần Thủy điện A Vương,AVHPC,A Vuong Hydropower Joint Stock Company,False,False,UPCOM,OTHER,"Utilities (Electricity, Water & Gas)"

In [41]:
df_info_new.rename(columns={'symbol': 'stock_code', 'full_name_vi': 'company_name', 'short_name_vi': 'short_name', 'english_name': 'en_company_name' }, inplace=True)

In [42]:
df_info_old_stock_code = set(df_info_old['stock_code'].unique())
df_info_new_stock_code = set(df_info_new['stock_code'].unique())

diff_info_stock_code = df_info_new_stock_code - df_info_old_stock_code

In [43]:
df_info_new_new = df_info_new[df_info_new['stock_code'].isin(diff_info_stock_code)]
df_info_new_new.head()

,stock_code,company_name,short_name,en_company_name,is_bank,is_securities,exchange,stock_indices,industry
0,ABC,Công ty Cổ phần Truyền thông VMG,VMG Media,VMG Media Joint Stock Company,False,False,UPCOM,OTHER,Media
2,AMS,Công ty Cổ phần Cơ khí Xây dựng AMECC,AMECC JSC,AMECC Mechanical Construction Joint Stock Company,False,False,UPCOM,OTHER,Industrial Goods and Services
3,APF,Công ty Cổ phần Nông sản Thực phẩm Quảng Ngãi,APFCO,Quang Ngai Agricultural Products and Foodstuff...,False,False,UPCOM,OTHER,Food and Beverages
4,AVC,Công ty Cổ phần Thủy điện A Vương,AVHPC,A Vuong Hydropower Joint Stock Company,False,False,UPCOM,OTHER,"Utilities (Electricity, Water & Gas)"
5,BCA,Công ty Cổ phần B.C.H,B.C.H,B.C.H Joint Stock Company,False,False,UPCOM,OTHER,Basic Resources

In [44]:
df_info_old = df_info_old[["stock_code", "company_name", "short_name", "industry", "exchange", "stock_indices", "is_bank", "is_securities", "en_company_name"]]

In [45]:
df_info_all = pd.concat([df_info_old, df_info_new_new], ignore_index=True)
df_info_all.head()

,stock_code,company_name,short_name,industry,exchange,stock_indices,is_bank,is_securities,en_company_name
0,BID,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,BIDV,Banking,HOSE,VN30,True,False,Joint Stock Commercial Bank for Investment and...
1,EIB,Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Vi...,Eximbank,Banking,HOSE,OTHER,True,False,Vietnam Export Import Commercial Joint Stock Bank
2,OCB,Ngân hàng Thương mại Cổ phần Phương Đông,Ngân hàng Phương Đông,Banking,HOSE,OTHER,True,False,Orient Commercial Joint Stock Bank
3,CTG,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,VietinBank,Banking,HOSE,VN30,True,False,Vietnam Joint Stock Commercial Bank For Indust...
4,VCB,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,Vietcombank,Banking,HOSE,VN30,True,False,Joint Stock Commercial Bank For Foreign Trade ...

In [46]:
df_info_all.to_csv('../data/df_company_info_v2.csv', index=False)